Feat/script rate limit (#56) add script for rate limit check and push to private local registry
* test local registry service

* ajoute docker configuration pour utiliser le mirroir sur chaque job

* replace localhost by docker-cache

* fix composer install for master. wait for docker registry to be ready

* revert sur le curl du registry

* push image to docker-cache

* move registry service into a simple step

* fix push tag name to localhost registry

* fix tag name creation

* remove test step for localhost registry

* remove localhost:5000 from image name destination

* remove REGISTRY_PROXY_REMOTEURL from registry

* test simple workflow with local registry

* test simple workflow with env params

* fix branch name = master

* insecure registry use http

* revert insecure registry, use global ENV

* add chatgpt workflow

* fix builder name

* fix buildx name

* fix registry name localhost

* use ghcr.io as registry cache

* fix ghcr.io registry name

* push same image to quay.io

* check Quay.io username and password

* upgrade docker/login-action:v3

* buildx with registry cache

* fix registry reference name

* fix registry ref and tag name

* multi registry push: add quay.io

* login to Quay.io before push

* login to ghcr.io before push

* login to docker.io before pull, and warm-up step

* branch trigger name

* checkout before the warm-up

* separe push steps to ghcr.io and quay.io

* fix current datetime and check errors on push

* fix current datetime, limit max-parallel=3

* remove useless summary, add full generation

* add quotes to special labels

* check rate limit  before and after

* protect cron command value with special characters

* move problematic labels into the merge job

* EOF syntax for github summary

* fix EOF syntax

* fix docker pull rate check and move registry cache to docker-jeedom repo

* add script_rate_limit

* fix script path

* registry mirror

* login to docker hub and ghcr.io and push to ghcr.io

* cache to ghcr.io

* fix cache-from cache-to typo

* fix final summary

* use registry mirror and script for rate limit

* loop to retry ghcr.io push

* test local mirror registry

* mirror with private registry

* test private repo

* matrix pull push to private repo

* docker login from stdin

* tag with platform name

* push images into private repo

* remove unsuccessfull mirror registry

* fix post repase

diff --git a/.github/workflows/buildx-platform.yml b/.github/workflows/buildx-platform.yml
--- a/.github/workflows/buildx-platform.yml
+++ b/.github/workflows/buildx-platform.yml
@@ -7,7 +7,6 @@ on:
     branches:
       - master
       - develop
-      - feat/improvment
   # this is to manually trigger the worklow
   workflow_dispatch:
     inputs:
@@ -38,11 +37,6 @@ jobs:
   initStep:
     runs-on: ubuntu-latest
     steps:
-      - name: Remove old artifacts
-        # https://github.com/marketplace/actions/remove-artifacts
-        uses: c-hive/gha-remove-artifacts@v1
-        with:
-          age: '10 seconds'
       -
         name: Checkout
         uses: actions/checkout@v4.1.2
@@ -63,58 +57,31 @@ jobs:
       -
         name: Login to DockerHub
         # https://github.com/marketplace/actions/docker-login
-        # login to DockerHub with login & secrets token - for pull to avoid error HTTP 429 Too many requests
+        # login to DockerHub with login & secrets token to get our private rate limit
         uses: docker/login-action@v3
         with:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: check Docker.io rate limit
+      - name: Run DockerHub rate limit check
+        id: ratecheck
         run: |
-          #!/usr/bin/env bash
-          # Vérifie la limite et le nombre de pulls restants sur Docker Hub
+          chmod +x .github/scripts/rate_limit.sh
+          ./.github/scripts/rate_limit.sh
 
-          # Dépendances : curl + jq
-          if ! command -v jq >/dev/null 2>&1; then
-            echo "❌ jq est requis (sudo apt install jq ou brew install jq)"
-            exit 1
-          fi
+      - name: Add summary to Job Summary
+        run: |
+          echo "### 🐳 DockerHub Pull Limit" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.ratecheck.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
 
-          # 1️⃣ Récupère un token d'authentification pour une image publique
-          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" \
-            | jq -r '.token')
-
-          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
-            echo "❌ Impossible d'obtenir un token Docker Hub"
-            exit 1
-          fi
-
-          # 2️⃣ Interroge le registre pour obtenir les infos de quota
-          HEADERS=$(curl -s -I -H "Authorization: Bearer $TOKEN" \
-            https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest)
-
-          # Exemple de lignes :
-          # RateLimit-Limit: 100;w=21600
-          # RateLimit-Remaining: 73;w=21600
-
-          # Extraire limite + fenêtre
-          read LIMIT WINDOW < <(echo "$HEADERS" | grep -i "RateLimit-Limit" | sed -E 's/.*: ([0-9]+);w=([0-9]+)/\1 \2/')
-          # Extraire le nombre restant
-          read REMAINING _ < <(echo "$HEADERS" | grep -i "RateLimit-Remaining" | sed -E 's/.*: ([0-9]+);w=([0-9]+)/\1 \2/')
-
-          # 3️⃣ Affiche un résumé propre
-          if [[ -n "$LIMIT" && -n "$REMAINING" && -n "$WINDOW" ]]; then
-            CURRENT_DATETIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
-            HOURS=$(awk "BEGIN {printf \"%.1f\", $WINDOW/3600}")
-            echo "✅ Pulls restants au ${CURRENT_DATETIME} : $REMAINING / $LIMIT (fenêtre de ${HOURS}h)"
-          else
-            echo "⚠️ Impossible de lire les en-têtes RateLimit"
-            echo "$HEADERS"
-          fi
+      - name: check Docker.io rate limit
+        if: ${{ steps.ratecheck.outputs.remaining && (steps.ratecheck.outputs.remaining < 10) }}
+        run: |
+          echo "⚠️ Il reste moins de 10 pulls : ${{ steps.ratecheck.outputs.remaining }} / ${{ steps.ratecheck.outputs.limit }}" >> $GITHUB_STEP_SUMMARY && exit 1
 
   jbuild:
     # https://docs.docker.com/build/ci/github-actions/multi-platform/
-    # distributebuild across multiple runners
+    # distribute build across multiple runners
     # This step  build the same image on different runners / platforms
     runs-on: ubuntu-latest
     needs: initStep
@@ -155,33 +122,12 @@ jobs:
     env:
       # tag name de la forme: debian-php-light-debug-dev e.g. bullseye-8.2-light-debug-dev
       TAG_NAME: ${{ matrix.debian }}-${{ matrix.php }}${{ matrix.target == 'light' && '-light' || '' }}${{ github.ref_name != 'master' && '-dev' || '' }}
-      TAG_LATEST_ENABLED: ${{ (matrix.debian == 'bullseye' && matrix.target == 'full' && matrix.target == 'full' && github.ref_name == 'master') }}
+      TAG_LATEST_ENABLED: ${{ (matrix.debian == 'bullseye' && matrix.target == 'full' && github.ref_name == 'master') }}
       CACHE_NAME: ${{ matrix.debian }}-${{ matrix.platform }}-${{ matrix.php }}
       # Référence vers le cache du registre
       REGISTRY_CACHE: ghcr.io/pifou25/docker-jeedom
 
     steps:
-      -
-        name: Prepare ${{ env.TAG_NAME }}:${{ matrix.platform }}
-        # replace /  by - in platform value and registry cache name
-        run: |
-          platform=linux/${{ matrix.platform }}
-          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
-          # echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_STEP_SUMMARY
-          echo "CACHE_TAG=buildcache-${CACHE_NAME//\//-}" >> $GITHUB_ENV
-          # echo "CACHE_TAG=buildcache-${CACHE_NAME//\//-}" >> $GITHUB_STEP_SUMMARY
-
-      # prepare image cache for Dockerfile buildx
-      # https://github.com/marketplace/actions/cache
-      - id: image-cache
-        uses: actions/cache@v4.2.2
-        with:
-          path: ~/image-cache
-          # Adjust key to meet your cache time requirements e.g.
-          # ${{ hashFiles(*) }} can be useful here to invalidate
-          # cache on file changes
-          key: image-cache-${{ runner.os }}${{ matrix.php }}${{ matrix.debian }}${{ matrix.platform }}
-
       -
         name: Login to DockerHub
         # https://github.com/marketplace/actions/docker-login
@@ -191,49 +137,19 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - if: steps.image-cache.outputs.cache-hit != 'true'
-        name: Pull images for ${{ env.CACHE_NAME }} and save in cache
-        # pull from docker hub if not in cache and save in cache
+      -
+        name: Prepare ${{ env.TAG_NAME }}:${{ matrix.platform }}
+        # replace /  by - in platform value and registry cache name
+        # list local registry mirror available images for debug
         run: |
-          # trim '/' from the cache name
-          CACHE_NAME=${CACHE_NAME//'/'/}
-          # echo "pull images for ${CACHE_NAME}" >> $GITHUB_STEP_SUMMARY
-          mkdir -p ~/image-cache # create cache directory
-          docker pull --platform linux/${{ matrix.platform }} php:${{ matrix.php }}-apache-${{ matrix.debian }}
-          docker pull --platform linux/${{ matrix.platform }} composer/composer:latest-bin
-          docker pull --platform linux/${{ matrix.platform }} mlocati/php-extension-installer
-          docker save -o ~/image-cache/php.${CACHE_NAME}.tar php:${{ matrix.php }}-apache-${{ matrix.debian }}
-          docker save -o ~/image-cache/php-extension-installer-${CACHE_NAME}.tar mlocati/php-extension-installer
-          docker save -o ~/image-cache/composer-${CACHE_NAME}.tar composer/composer:latest-bin
-          # sleep to avoid HTTP 429 error (too many requests...)
-          # sleep 1m
-
-      - if: steps.image-cache.outputs.cache-hit == 'true'
-        name: Load images from cache for ${{ env.CACHE_NAME }}
-        # load from cache
-        run: |
-          # trim '/' from the cache name
-          CACHE_NAME=${CACHE_NAME//'/'/}
-          # echo "load images from cache for ${CACHE_NAME}" >> $GITHUB_STEP_SUMMARY
-          docker load -i ~/image-cache/php.${CACHE_NAME}.tar
-          docker load -i ~/image-cache/php-extension-installer-${CACHE_NAME}.tar
-          docker load -i ~/image-cache/composer-${CACHE_NAME}.tar
+          platform=linux/${{ matrix.platform }}
+          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
+          echo "CACHE_TAG=buildcache-${CACHE_NAME//\//-}" >> $GITHUB_ENV
 
       -
         name: Checkout
-        uses: actions/checkout@v4.1.2
+        uses: actions/checkout@v4
           
-      - name: Warm-up build (fills local daemon cache)
-        # étape de préchauffage du cache docker
-        run: |
-          docker buildx build --load \
-            --platform linux/amd64 \
-            --build-arg DEBIAN=${{ matrix.debian }} \
-            --build-arg PHP=${{ matrix.php }} \
-            --network=host \
-            --file build/Dockerfile \
-            build
-
       - 
         name: Login to GitHub Container Registry
         # 🔹 Service de cache Docker Registry ghcr.io
@@ -242,7 +158,7 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GHCR_SECRET }}
-        
+
       -
         name: Docker meta
         id: meta
@@ -270,7 +186,6 @@ jobs:
         # set up a multi-platform builder for Docker containers
         uses: docker/setup-buildx-action@v3
         with:
-          driver-opts: network=host
           buildkitd-flags: --debug
           install: true
           driver: docker-container
@@ -362,7 +277,7 @@ jobs:
 
     env:
       TAG_NAME: ${{ matrix.debian }}-${{ matrix.php }}${{ matrix.target == 'light' && '-light' || '' }}${{ github.ref_name != 'master' && '-dev' || '' }}
-      TAG_LATEST_ENABLED: ${{ (matrix.debian == 'bullseye' && matrix.target == 'full' && matrix.target == 'full' && github.ref_name == 'master') }}
+      TAG_LATEST_ENABLED: ${{ (matrix.debian == 'bullseye' && matrix.target == 'full' && github.ref_name == 'master') }}
 
     steps:
       - name: init datetime value
@@ -409,23 +324,11 @@ jobs:
             chadburn.enabled=true
             chadburn.job-exec.jeedom-cron.schedule=@every 1m
             chadburn.job-exec.jeedom-cron.command="/usr/local/bin/php /var/www/html/core/php/jeeCron.php >> /var/www/html/log/cron.log 2>&1"
-
-      -
-        name: Login to DockerHub
-        # https://github.com/marketplace/actions/docker-login
-        # login to DockerHub with secrets login & token
-        uses: docker/login-action@v3
-        with:
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
  
       -
         name: Create manifest list and push ${{ env.TAG_NAME }}
         working-directory: /tmp/digests
         run: |
-          # debug tmp directory
-          ls /tmp -alsh
-          echo jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON"
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
             $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
 
@@ -444,10 +347,21 @@ jobs:
         # continue to next step even in case of error
         continue-on-error: true
         run: |
-          docker buildx imagetools create \
-            ${{ env.TAG_LATEST_ENABLED && '--tag ghcr.io/${REGISTRY_IMAGE}:latest' || '' }} \
-            --tag ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }} \
-            ${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }}
+            attempt=0
+            max_attempts=5
+            until docker buildx imagetools create \
+              ${{ env.TAG_LATEST_ENABLED == true && '--tag ghcr.io/${REGISTRY_IMAGE}:latest' || '' }} \
+              --tag ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }} \
+              ${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }}
+            do
+              attempt=$((attempt+1))
+              if [ "$attempt" -ge "$max_attempts" ]; then
+                echo "❌ Trop de tentatives, abandon. (${attempt})" >> $GITHUB_STEP_SUMMARY
+                exit 1
+              fi
+              echo "⚠️ Erreur 429, attente avant retry (${attempt})..." >> $GITHUB_STEP_SUMMARY
+              sleep $((attempt * 10))  # pause progressive : 10s, 20s, 30s…
+            done
 
       -
         name: Login to Quay.io
@@ -457,7 +371,7 @@ jobs:
           username: ${{ secrets.QUAY_USER }}
           password: ${{ secrets.QUAY_PASSWORD }}
          
-      - name: Push image to Quay.io
+      - name: Push ${{ env.TAG_NAME }} to Quay.io
         id: quay-push
         # continue to next step even in case of error
         continue-on-error: true
@@ -465,6 +379,24 @@ jobs:
           docker buildx imagetools create \
             ${{ env.TAG_LATEST_ENABLED && '--tag quay.io/${REGISTRY_IMAGE}:latest' || '' }} \
             --tag quay.io/${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }} \
+            ${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }}
+      -
+        name: Login to nico private repository
+        # https://github.com/marketplace/actions/docker-login
+        uses: docker/login-action@v3
+        with:
+          registry: reg.nico.si
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.NICO_PASSWORD }}
+         
+      - name: Push image to nico.si
+        id: nico-push
+        # continue to next step even in case of error
+        continue-on-error: true
+        run: |
+          docker buildx imagetools create \
+            ${{ env.TAG_LATEST_ENABLED == true && '--tag reg.nico.si/${REGISTRY_IMAGE}:latest' || '' }} \
+            --tag reg.nico.si/${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }} \
             ${{ env.REGISTRY_IMAGE }}:${{ env.TAG_NAME }}
 
       - name: Check push into quay.io ${{ env.TAG_NAME }}
@@ -480,7 +412,11 @@ jobs:
           else \
             echo "Successfull pushing ${TAG_NAME} to quay.io 🚀" >> $GITHUB_STEP_SUMMARY; \
           fi
-          exit 1
+          if [ "${{ steps.nico-push.outcome }}" != "success" ]; then \
+            echo "Fail pushing ${TAG_NAME} to nico.si ! 🚀 ( ?? )" >> $GITHUB_STEP_SUMMARY; \
+          else \
+            echo "Successfull pushing ${TAG_NAME} to nico.si 🚀" >> $GITHUB_STEP_SUMMARY; \
+          fi
 
   conclusion:
     # login to Docker.io and check remaining rate limit
@@ -498,45 +434,18 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: check Docker.io rate limit
+      - name: Run DockerHub rate limit final check
+        id: ratecheckFinal
         run: |
-          #!/usr/bin/env bash
-          # Vérifie la limite et le nombre de pulls restants sur Docker Hub
+          chmod +x .github/scripts/rate_limit.sh
+          ./.github/scripts/rate_limit.sh
 
-          # Dépendances : curl + jq
-          if ! command -v jq >/dev/null 2>&1; then
-            echo "❌ jq est requis (sudo apt install jq ou brew install jq)"
-            exit 1
-          fi
-
-          # 1️⃣ Récupère un token d'authentification pour une image publique
-          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" \
-            | jq -r '.token')
-
-          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
-            echo "❌ Impossible d'obtenir un token Docker Hub"
-            exit 1
-          fi
-
-          # 2️⃣ Interroge le registre pour obtenir les infos de quota
-          HEADERS=$(curl -s -I -H "Authorization: Bearer $TOKEN" \
-            https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest)
-
-          # Exemple de lignes :
-          # RateLimit-Limit: 100;w=21600
-          # RateLimit-Remaining: 73;w=21600
-
-          # Extraire limite + fenêtre
-          read LIMIT WINDOW < <(echo "$HEADERS" | grep -i "RateLimit-Limit" | sed -E 's/.*: ([0-9]+);w=([0-9]+)/\1 \2/')
-          # Extraire le nombre restant
-          read REMAINING _ < <(echo "$HEADERS" | grep -i "RateLimit-Remaining" | sed -E 's/.*: ([0-9]+);w=([0-9]+)/\1 \2/')
-
-          # 3️⃣ Affiche un résumé propre
-          if [[ -n "$LIMIT" && -n "$REMAINING" && -n "$WINDOW" ]]; then
-            CURRENT_DATETIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
-            HOURS=$(awk "BEGIN {printf \"%.1f\", $WINDOW/3600}")
-            echo "✅ Pulls restants au ${CURRENT_DATETIME} : $REMAINING / $LIMIT (fenêtre de ${HOURS}h)"
-          else
-            echo "⚠️ Impossible de lire les en-têtes RateLimit"
-            echo "$HEADERS"
-          fi
+      - name: Add summary to Job Summary
+        run: |
+          echo "### 🐳 DockerHub Pull Limit" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.ratecheckFinal.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
+      - name: Remove useless artifacts
+        # https://github.com/marketplace/actions/remove-artifacts
+        uses: c-hive/gha-remove-artifacts@v1
+        with:
+          age: '5 seconds'
diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -2,7 +2,7 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ none ]
+    branches: [ feat/script_rate_limit ]
   pull_request:
     branches: [ none ]
   # this is to manually trigger the worklow
@@ -12,6 +12,23 @@ on:
         description: 'Reason'     
         default: 'Manual launch'
 
+env:
+  # used to download jeedom source
+  # JEEDOM_REPO: ${{ github.ref_name == 'master' && 'jeedom/core' || 'pifou25/jeedom-core' }}
+  JEEDOM_REPO: jeedom/core
+  # branch to use: master if the current branch is master, develop if not
+  # this is used to set the jeedom version in the Dockerfile
+  # JEEDOM_BRANCH: ${{ github.ref_name == 'master' && 'master' || 'develop' }}
+  JEEDOM_BRANCH: master
+  # destination docker registry image name
+  REGISTRY_IMAGE: pifou25/jeedom
+  # XDEBUG enabled by default for develop and beta branches
+  XDEBUG: ${{ github.ref_name == 'master' && 'false' || 'true' }}
+  DEBIAN: trixie
+  PHP: 8.4
+  DOCKER_BUILDKIT: 1
+  BUILDKIT_INSECURE_REGISTRY: registry:5000
+
 jobs:
 
   build:
@@ -19,19 +36,9 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-        options: >-
-          --health-cmd "wget --spider -q http://localhost:5000/v2/ || exit 1"
-          --health-interval 5s
-          --health-retries 10
-          
     env:
       DOCKER_BUILDKIT: 1
-      BUILDKIT_INSECURE_REGISTRY: registry:5000
+      BUILDKIT_INSECURE_REGISTRY: registry-mirror:5000
       # used to download jeedom source
       # JEEDOM_REPO: ${{ github.ref_name == 'master' && 'jeedom/core' || 'pifou25/jeedom-core' }}
       JEEDOM_REPO: jeedom/core
@@ -45,25 +52,93 @@ jobs:
       XDEBUG: ${{ github.ref_name == 'master' && 'false' || 'true' }}
       DEBIAN: trixie
       PHP: 8.4
+      # Référence vers le cache du registre
+      REGISTRY_CACHE: ghcr.io/pifou25/docker-jeedom
+      CACHE_NAME: trixie-8.4
+      
+    # continue to next job even if there are some errors in jbuild job
+    continue-on-error: true
+    strategy:
+      # do every matrix combination, don't stop on errors
+      fail-fast: false
+      # limit to avoid error HTTP 409: too many requests
+      max-parallel: 2
+      matrix:
+        # target: ["light" , "full"]
+        debian: [bullseye, bookworm, trixie]
+        php: [7.4, 8.2, 8.4]
+        # linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
+        platform: [amd64, arm64, arm/v6, arm/v7]
+        # only build bullseye with php7.4, bookworm with php8.2 and trixie with php8.4
+        exclude:
+          - debian: bookworm
+            php: 7.4
+          - debian: bookworm
+            php: 8.4
+          - debian: bullseye
+            php: 8.2
+          - debian: bullseye
+            php: 8.4
+          - debian: trixie
+            php: 8.2
+          - debian: trixie
+            php: 7.4
 
     steps:
 
-      # prepare image cache for local registry
-      # https://github.com/marketplace/actions/cache
-      - id: image-cache
-        uses: actions/cache@v4.2.2
-        with:
-          path: /tmp/registry-cache
-          key: registry-cache
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-      # local registry for docker cache
-      #- name: Start local Docker registry (mirror/cache)
-      #  run: |
-      #    docker network create buildnet
-      #    docker run -d -p 5000:5000 --restart=always --name registry \
-      #      --network buildnet -v /tmp/docker-registry:/var/lib/registry \
-      #      registry:2
-      #    npx wait-on tcp:5000
+      -
+        name: Login to nico private repository
+        # https://github.com/marketplace/actions/docker-login
+        uses: docker/login-action@v3
+        with:
+          registry: reg.nico.si
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.NICO_PASSWORD }}
+
+      # pull image from docker hub and check it is available into the registry-mirror
+      - name: Test private repository
+        run: |
+         docker pull php:${{ matrix.php }}-apache-${{ matrix.debian }} --platform linux/${{ matrix.platform }}
+         docker tag php:${{ matrix.php }}-apache-${{ matrix.debian }} reg.nico.si/php:${{ matrix.php }}-apache-${{ matrix.debian }}-${{ matrix.platform }}
+         docker push reg.nico.si/php:${{ matrix.php }}-apache-${{ matrix.debian }}-${{ matrix.platform }}
+         exit 1
+
+      -
+        name: Login to DockerHub
+        # https://github.com/marketplace/actions/docker-login
+        # login to DockerHub with login & secrets token - for pull to avoid error HTTP 429 Too many requests
+        uses: docker/login-action@v3
+        with:
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - 
+        name: Login to GitHub Container Registry
+        # 🔹 Service de cache Docker Registry ghcr.io
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GHCR_SECRET }}
+        
+      - name: Run DockerHub rate limit check
+        id: ratecheck
+        run: |
+          chmod +x .github/scripts/rate_limit.sh
+          ./.github/scripts/rate_limit.sh
+
+      - name: Add summary to Job Summary
+        run: |
+          echo "### 🐳 DockerHub Pull Limit" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.ratecheck.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
+
+      - name: check Docker.io rate limit
+        if: ${{ steps.ratecheck.outputs.remaining && (steps.ratecheck.outputs.remaining < 10) }}
+        run: |
+          echo "⚠️ Il reste moins de 10 pulls : ${{ steps.ratecheck.outputs.remaining }} / ${{ steps.ratecheck.outputs.limit }}" >> $GITHUB_STEP_SUMMARY && exit 1
 
       - name: Set up Docker Buildx
         # https://github.com/marketplace/actions/docker-setup-buildx
@@ -73,17 +148,14 @@ jobs:
           name: jeedom-builder
           buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
           buildkitd-config-inline: |
-            [registry."registry:5000"]
+            [registry."registry-mirror:5000"]
               http = true
               insecure = true
-
-      - uses: actions/checkout@v4.1.2
 
       #- name: Enable buildx
       #  run: |
       #    docker buildx create --use --name jeedom-builder --driver docker-container --driver-opt network=buildnet
       #    docker buildx inspect --bootstrap
-
       - name: Build with cache using previous builder
         # docker build --builder [name] --build-arg [arg=value] --file [file] --tag [tag] [directory]
         run: |
@@ -94,18 +166,23 @@ jobs:
             --build-arg JEEDOM_VERSION=${{ env.JEEDOM_BRANCH }} \
             --build-arg XDEBUG=false \
             --build-arg XTRARGS=-light \
-            --cache-from type=registry,ref=registry:5000/${{ env.REGISTRY_IMAGE }}:buildcache \
-            --cache-to type=registry,ref=registry:5000/${{ env.REGISTRY_IMAGE }}:buildcache,mode=max \
+            --cache-from type=registry,ref=${{ env.REGISTRY_CACHE }}:${{ env.CACHE_NAME }} \
+            --cache-to type=registry,ref=${{ env.REGISTRY_CACHE }}:${{ env.CACHE_NAME }},mode=max \
             --file build/Dockerfile \
-            --tag registry:5000/${{ env.REGISTRY_IMAGE }}:test \
+            --tag ghcr.io/${{ env.REGISTRY_IMAGE }}:test \
             --load build
 
       - name: Docker Push
         run: |
-          docker push registry:5000/${{ secrets.DOCKER_USER }}/jeedom:test
-
-      - name: docker push to Docker.io
+          docker push ghcr.io/${{ secrets.DOCKER_USER }}/jeedom:test
+        
+      - name: Run DockerHub rate limit final check
+        id: ratecheckFinal
         run: |
-          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} 
-          docker tag registry:5000/${{ secrets.DOCKER_USER }}/jeedom:test ${{ secrets.DOCKER_USER }}/jeedom:test
-          docker push ${{ secrets.DOCKER_USER }}/jeedom:test
+          chmod +x .github/scripts/rate_limit.sh
+          ./.github/scripts/rate_limit.sh
+
+      - name: Add summary to Job Summary
+        run: |
+          echo "### 🐳 DockerHub Pull Limit" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.ratecheckFinal.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
